### PR TITLE
PR for Power Update for S0

### PR DESCRIPTION
**Pull request by ldxib2**

### CODE REVIEW

**Comment by Femkemilene** [comment]
Hi Ian,

Can you make sure S1 and S2 are also updated? The model may crash if we accept this PR as is. There is an option for a draft pull request if you'd like eyes on an update and you need to do the finishing touches still.

Femke
________________________________
From: Ian Burton ***@***.***>
Sent: 10 April 2024 14:09
To: cpmodel/FTT_StandAlone ***@***.***>
Cc: Nijsse, Femke ***@***.***>; Review requested ***@***.***>
Subject: [cpmodel/FTT_StandAlone] PR for Power Update for S0 (PR #113)

CAUTION: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/cpmodel/FTT_StandAlone/pull/113

Commit Summary

  *   68cdede<https://github.com/cpmodel/FTT_StandAlone/pull/113/commits/68cdedef193c6b159cb1abf701597f66b0e63861> power update S0
  *   7ab61a7<https://github.com/cpmodel/FTT_StandAlone/pull/113/commits/7ab61a745c797fb6069398c519a5f45d31b1623c> Add histend for BCET
  *   b21bbd4<https://github.com/cpmodel/FTT_StandAlone/pull/113/commits/b21bbd4dcd62e7ea1806cc4559994a42ee907573> input files temporary
  *   85c5df1<https://github.com/cpmodel/FTT_StandAlone/pull/113/commits/85c5df16923d85d198ddb09475f1407e945d87fd> masterfile formulas cleaned and gamma extraction code added
  *   b2d7f0e<https://github.com/cpmodel/FTT_StandAlone/pull/113/commits/b2d7f0e07ad40304748d595ff7dc81ed54dcd2ac> gamma extract code extended
  *   4967a0c<https://github.com/cpmodel/FTT_StandAlone/pull/113/commits/4967a0cca1b47b7e1bbaaf1587827376cc554286> finished gamma extract file and changes made to master2023
  *   4915d3c<https://github.com/cpmodel/FTT_StandAlone/pull/113/commits/4915d3cbf0a34c905d9462746c521a93cd5aaeea> Final save of gammas
  *   4179fe1<https://github.com/cpmodel/FTT_StandAlone/pull/113/commits/4179fe1bafb17318799735cb39a649d475e129e5> Update .gitignore
  *   94f9a4a<https://github.com/cpmodel/FTT_StandAlone/pull/113/commits/94f9a4a0c4b8daa7a8d7ea58be0f10578006161e> Unnecessary code removed
  *   0726d46<https://github.com/cpmodel/FTT_StandAlone/pull/113/commits/0726d468f4b1b172023c9b1922f6d28ed45c89aa> Change gitignore location
  *   bfd6688<https://github.com/cpmodel/FTT_StandAlone/pull/113/commits/bfd6688351dd653202a7a261901e021f1d8bada6> removal of new csvs for update check
  *   1d9a6a9<https://github.com/cpmodel/FTT_StandAlone/pull/113/commits/1d9a6a950e3ec14e4f67ae0e7cbbad77c46f44cc> Resave of gitignore

File Changes

(8 files<https://github.com/cpmodel/FTT_StandAlone/pull/113/files>)

  *   M Inputs/.gitignore<https://github.com/cpmodel/FTT_StandAlone/pull/113/files#diff-1b0f7a1b6e56ff86a50ef975d635fc627f62928cd306b9804d6a091664747e2e> (2)
  *   A Inputs/_MasterFiles/FTT-P/FTT-P-24x71_2023_S0.xlsx<https://github.com/cpmodel/FTT_StandAlone/pull/113/files#diff-957e5c63fea074e2851ec1f56ff3633d3471b50d4bb70a25b7c832d631ef208e> (0)
  *   M Output/Gamma.json<https://github.com/cpmodel/FTT_StandAlone/pull/113/files#diff-a2144573dc21e7fb816adeb1393f122504f9e8c67c66bc5dec420b1126cdfddb> (2)
  *   M SourceCode/Power/ftt_p_main.py<https://github.com/cpmodel/FTT_StandAlone/pull/113/files#diff-f6f195020d130035feffb2a1b4959eaa2871c0b77d3414bddc7255208e168c16> (17)
  *   M SourceCode/support/convert_masterfiles_to_csv.py<https://github.com/cpmodel/FTT_StandAlone/pull/113/files#diff-c1a8e7d62e38dc80ff7203dfacc78098321bc8926a73c1ba80bbe134c3341139> (2)
  *   M Utilities/titles/VariableListing.csv<https://github.com/cpmodel/FTT_StandAlone/pull/113/files#diff-2f401df94acc02c6ebf5376a7db8c67578efcad26aac71534b81511e3b9aef8c> (4)
  *   A gam_pkl_extract_master_save.py<https://github.com/cpmodel/FTT_StandAlone/pull/113/files#diff-3e4ad07738bd7f8e081cdccbaab50dfa2b114c1e6a65e7e5c725919f40b77111> (135)
  *   M settings.ini<https://github.com/cpmodel/FTT_StandAlone/pull/113/files#diff-f247846b0ab6c196467cd7e8e41027c7f27eb2b74b2e9a33d54c59a6fe9f00b0> (6)

Patch Links:

  *   https://github.com/cpmodel/FTT_StandAlone/pull/113.patch
  *   https://github.com/cpmodel/FTT_StandAlone/pull/113.diff

**Comment by Femkemilene** [comment]
Can you show a comparison with some key variables between the old and new model? Is this in the direction we're expecting the change. The key differences I expect are:
* More gas globally. Prices are significantly less than before
* Maybe less solar/wind? In this version, the error of when learning starts has been corrected.

**Comment by ldxib2** [comment]
S0_2022:

Untitled

S0_2024:

Untitled

**Comment by ldxib2** [comment]
S2_2024_global_shares
S2_2024_global_shares
S2_2024_global_cap
S2_2024_global_cap
S2_2024_LCOE_US
S2_2024_LCOE_US
S2_2024_LCOE_CN
S2_2024_LCOE_CN

**Comment by Femkemilene** [comment]
@ldxib2: why are solar prices in the US going down this suddenly (S0)? And why is the costs of offshore wind going up in the US and in China in the S2 scenarios? Is something going wrong with the capacity factor calculations? There are some less pronounced oddities in the old version too.

**Review by Femkemilene — CHANGES_REQUESTED** [review]
Let's figure out where the discontuity stems from first and correct it.

**Comment by ldxib2** [comment]
Issues with the S2 raise in price have been corrected. MEFI was being added in the LCOE script instead of subtracted. Hotfix was created to sort this in the main branch and here too. S2 graphs above are now obsolete. Cause of S0 drop in solar price is still to be determined

**Comment by ldxib2** [comment]
After mcsc hotfix comparison outputs

S0_2022_CN_LCOE

S0_2022_CN_LCOE

S0_2024_CN_LCOE

S0_2024_CN_LCOE

S0_2022_US_LCOE

S0_2022_US_LCOE

S0_2024_US_LCOE

S0_2024_US_LCOE

S0_2022_MEWW

S0_2022_MEWW

S0_2024_MEWW

S0_2024_MEWW

S0_2022_global_shares

S0_2022_global_shares

S0_2024_global_shares

S0_2024_global_shares

**Review by Femkemilene — APPROVED** [review]

**Comment by Femkemilene** [comment]
I see nothing worrying in these changes. Surprisingly little has changed after the model update. To make life easier for ourselves, we can choose to first figure out the differences between main and FORTRAN before merging the updated data.

**Comment by pv-camecon** [comment]
I'll investigate model differences this week. Suspects are:
- Electricity demand
- The aforementioned potentials
- Learning-by-doing applied to just CAPEX in the Fortran version

**Comment by Femkemilene** [comment]
I've been comparing to 2022_baseline_update, which does have LBD in both CAPEX and OPEX. I also checked the capacity factors from the cost-supply curves: they're the same between the two model versions.

**Review by jp-camecon — CHANGES_REQUESTED** [review]
Unless I am missing something, the current version committed does run correctly. I am getting a silent model crash due to issues in 2022 as storage cost becoming NaN implying most likely a div zero error has occurred. Can someone please test checking out a clean version of this and confirm the same issue.

Specifically I see the issue in regions 56, 62-71.

**Comment by pv-camecon** [comment]
> Unless I am missing something, the current version committed does run correctly. I am getting a silent model crash due to issues in 2022 as storage cost becoming NaN implying most likely a div zero error has occurred. Can someone please test checking out a clean version of this and confirm the same issue.
> 
> Specifically I see the issue in regions 56, 62-71.

This is due to empty cells for onshore and offshore wind power in 2022 in the master files for all regions. Something went wrong there when bringing over the new data.

**Comment by ldxib2** [comment]
I have just checked out this branch and I was able to run it even with the missing data. We don't have data for 2022 in this update as we stop at 2021. I checked the histend dates and they are fine too. Have you tried just filling the empty cells with random data, maybe copying from another masterfile just so there is something in there? I'm working on the belief it shouldn't change anything based on the 2021 histend

**Comment by jp-camecon** [comment]
> I have just checked out this branch and I was able to run it even with the missing data. We don't have data for 2022 in this update as we stop at 2021. I checked the histend dates and they are fine too. Have you tried just filling the empty cells with random data, maybe copying from another masterfile just so there is something in there? I'm working on the belief it shouldn't change anything based on the 2021 histend

When you ran this through, were you able to view results through to 2050? When I download this branch as it stands, it runs through to completion, but the results are NaN after 2022

**Comment by pv-camecon** [comment]
The input function will read in the whole timeline and that's where the NaNs get included despite occurring after histend. Presumably, the variable is used somewhere before it is overwritten and this introduces NaNs everywhere else.

________________________________

**Comment by jp-camecon** [comment]
To follow up. Pim shared with me the earlier discussion that the issue I am having can be resolved by doing a manual update of the csv file by running SourceCode / support / convert_masterfiles_to_csv.py. I will review the output as it stands and if that is fine I will accept this update and then we look at the refresh of csv files once we have dealt with the rest of the FTT power update.

**Comment by ldxib2** [comment]
I ran the convert_csv_files.py first too. I believe that this file was updated on one of the other branches, maybe explore_differences_fttp? That update was designed to check if the input files need updating automatically based on when the last changes to the masterfile were. If I am right then when we accept this update, then bring in the alignment changes with the generic sales PR then it should be brought in

**Comment by jp-camecon** [comment]
Overall, the version looks fine to me. There are a few calibration questions around uptake but we can resolve these in the new data update.

Only issue is I cannot approve the merge request due to the branch conflicts flagged by GitHub. Looks like these need to be handle via command line. Does anyone have any experience dealing with these conflicts like this?

**Comment by ldxib2** [comment]
you can do it from the command line or in the Github desktop manager also, it will just open the 2 versions of the document that the conflicts are on and highlight for you the difference between the HEAD branch and the incoming update from the branch you are merging. Then you choose or edit for each one, it's quite straight forward in the desktop. However, I'm unsure why some of the things are registered as conflicts as they seem like any other update

**Comment by jp-camecon** [comment]
Can you 

> you can do it from the command line or in the Github desktop manager also, it will just open the 2 versions of the document that the conflicts are on and highlight for you the difference between the HEAD branch and the incoming update from the branch you are merging. Then you choose or edit for each one, it's quite straight forward in the desktop. However, I'm unsure why some of the things are registered as conflicts as they seem like any other update

Can you please then resolve these conflicts Ian so we can carry out the merge then?

**Comment by ldxib2** [comment]
If you're happy for me to do that then sure! I will have a look tomorrow.

**Comment by ldxib2** [comment]
Hi both, apologies for the delay. I wasn't able to resolve the conflicts with the main branch without actually merging and I assumed you final say on it and I'm not even sure I can as I'm not a registered reviewer. So I copied the current main branch to a new one, pr_merge_main_base, then merged it see the conflicts and resolve them. Here is a summary:
Conflicts:
get_exog - kept main version 
gitignore - kept main version (includes REXX)
inititalise_csv - kept main version, no real changes 
ftt_lcoe_p - kept main version, changes in PR seem uneccessary and maybe older? and assuming these will be overwritten in alignment changes
convert_csvs - taken incoming PR changes, appears more recent with extra conditions related to last edits of inputs
VariableListing.csv - hard to see conflicts due to being csv, but appears to just be updated histend for MEWG

We can either make a new PR for this new branch that should go straight into main, or if you want to complete this PR you can assign me as a reviewer and I can redo the changes assuming you are ok with them?

Let me know your thoughts. Cheers!

**Comment by Femkemilene** [comment]
This is superseded by the new update

**Pull request closed without merging**
